version: "3.8"

services:
  distributor:
    build:
      context: ../
      dockerfile: ./distributor/Dockerfile
    ports:
      - 4000:4000
    container_name: distributor
    networks:
      - services

networks:
  services:
    name: makoto_micro
    external: true
