name: frontend/home
run-name: ${{ github.actor }} runs frontend/home tests
on: [push]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest


      - name: Cypress setu and App build
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend/home
          start: node .output/server/index.mjs # relying on the docs: https://nuxt.com/docs/getting-started/deployment and command line log
          build: pnpm build
          browser: chrome
